INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Garden Hose', 'outdoor', '15.12', '5');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Shoes', 'clothing', '20.72', '15');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Socks', 'clothing', '5.12', '25');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('tshirt', 'clothing', '15.52', '500');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Dog Food', 'pets', '25.38', '52');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Shampoo', 'HBA', '17.20', '55');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Gaming Mouse', 'electronics', '85.72', '8');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('electric drill', 'hardware', '105.92', '7');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('laundry soap', 'paper and cleaner', '25.13', '5');
INSERT INTO `bamazonDB`.`products` (`product_name`, `deprtment_name`, `price`, `stock_quantity`) VALUES ('Instant Pot', 'Household kitchen', '105.12', '3');